<a href="https://colab.research.google.com/github/sriram2728/Accenture-learning-modules/blob/master/CSIT553_class3_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSIT 553 Class 3 Exercise: Data Merging

In [1]:
# only run once
!git clone https://github.com/profliuhao/CSIT553.git

Cloning into 'CSIT553'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 148 (delta 59), reused 50 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (148/148), 4.34 MiB | 7.22 MiB/s, done.
Resolving deltas: 100% (59/59), done.

### Instruction
There are two datasets in this assignment:
1. **Energy_Indicators.csv** contains a list of indicators of energy supply and the percentage of renewable electricity production from the United Nations for the year 2013.
2. **Global_GDP.csv** contains countries' GDP from 1960 to 2017 from Wold Bank.

The following cell is set to load above two datasets as DataFrames: **energy** and **gdp**. Please execute it before working on the following questions. The two DataFrames **energy** and **gdp** can be used directly.

In [3]:
# Don't delete this cell
# Execute this cell to import pandas & numpy, and load data to DataFrames.


import pandas as pd
import numpy as np


pd.options.display.max_rows = 10
# energy=pd.read_csv('Energy_Indicators.csv')

energy=pd.read_csv('/content/CSIT553/Module_3/CSIT553_class3_1_exercise/Energy_Indicators.csv')

# gdp = pd.read_csv("Global_GDP.csv")

gdp = pd.read_csv("/content/CSIT553/Module_3/CSIT553_class3_1_exercise/Global_GDP.csv")

In [ ]:
energy

,Country Name,Energy Supply,Energy Supply per capita,Renewable Percentage
0,Afghanistan,321,10,78.67
1,Albania,102,35,100.00
2,Algeria,1959,51,0.55
3,American Samoa,...,...,0.64
4,Andorra,9,121,88.70
...,...,...,...,...
222,Viet Nam,2554,28,45.32
223,Wallis and Futuna Islands,0,26,0.00
224,Yemen,344,13,0.00
225,Zambia,400,26,99.71
226,Zimbabwe,480,32,52.54

In [4]:
gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.417804e+10,7.549239e+10,8.252614e+10,1.040000e+11,1.140000e+11,1.250000e+11,1.270000e+11,1.030000e+11,9.533720e+10,1.240000e+11
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.687488e+09,5.653793e+09,5.829934e+09,6.686683e+09,6.500193e+09,7.073420e+09,7.386891e+09,6.439947e+09,6.715487e+09,7.128691e+09
260,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.540133e+10,4.041524e+10,4.322858e+10,3.460248e+10,1.821333e+10,NaN
261,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,7.575248e+09,7.972841e+09,8.497830e+09,9.423212e+09,1.037379e+10,1.133417e+10,...,2.870000e+11,2.970000e+11,3.750000e+11,4.170000e+11,3.960000e+11,3.670000e+11,3.510000e+11,3.180000e+11,2.960000e+11,3.490000e+11
262,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10
263,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,4.415703e+09,8.621574e+09,1.014186e+10,1.209845e+10,1.424249e+10,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10

## Exercise 1
Clean the data in the DataFrame **Energy**. The detailed steps are as follows.  
  
#### Steps:   
1. For all the countries which have missing data (e.g., data with '...'), represent them as np.NaN values.
2. Rename the following list of countries:
        "Republic of Korea": "South Korea",
        "United States of America": "United States",
        "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
        "China, Hong Kong Special Administrative Region": "Hong Kong"

In [ ]:
energy = energy.replace('...',np.nan)

energy['Country Name'] = energy['Country Name'].replace({
    "Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
})

####  Execute the following statements
1. Because of '...' in the original data, the columns 'Energy Supply' and 'Energy Supply per capita' are recognized as strings. Use **astype** to convert them to be floating point number.
2. "Energy Supply" is in petajoules but "Energy Supply per capita" is in gigajoules. Convert the "Energy Supply" to gigajoules (there are 1,000,000 gigajoules in a petajoule).

In [ ]:
energy['Energy Supply'] = energy['Energy Supply'].astype(float)
energy['Energy Supply per capita'] = energy['Energy Supply per capita'].astype(float)
energy["Energy Supply"] = energy["Energy Supply"]*1000000

## Exercise 2
Process the DataFrame **gdp**. The detailed steps are as follows.  
  
#### Steps:   
1. Rename the following list of countries in "Country Name":
        "Korea, Rep.": "South Korea",
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"
2. Copy the column "Country Name" and the last 5 years (2013-2017) of GDP data to the DataFrame **GDP**.

## Exercise 3
 Create a new DataFrame **energyGDP** to merge the dataset **energy** and **GDP**.Set the column "Country Name" to be the index of **energyGDP**.
  
#### Steps:   
1. Merge **energy** and **GDP** with the key "Country Name".
2. Set the column "Country Name" to be the index of **energyGDP**.

### Exercise 4
Create two new columns in energeGDP.

Steps:
1. Create a new column called "Mean GDP" which records the average GDP in the last 5 years (2013-2017).
2. Create a new column called "E2GRatio" which records the ratio of "Energy Supply" to "Mean GDP".